### ISSUE TITLE
Option to disable extract functionality?

### ISSUE THREAD

**Issue by LRSFC-DanJ** [MScholtes/Win-PS2EXE#1]
Currently, it appears the executables produced by Win-PS2EXE are able to accept an "extract" switch which allows end users to extract the original PowerShell script from the executable. Would it be possible to add a checkbox option in the GUI for generating executables that do not contain this option?

**Comment by MScholtes** [comment]
Hello LRSFC-DanJ,

I am a great friend of free software, and I do not see the necessity to present an option to generate unfree software.

If you want ot do it by yourself: edit ps2exe.ps1 and replace the line
  if (!string.IsNullOrEmpty(extractFN))
with
  if (false)

Greetings

Markus

**Comment by Jayjaybb** [comment]
Hi MScholtes, thank you for this workaround.

PS: This project might survive more than you expected since new gen AV are coming up quickly on the market. 
*Also, IT administrator, with every AV product can easly whitelist the exe generated.

And for exemple, in my test env, ps2exe compiled script are not flagged as virus by my new gen AV since the operation has a normal behiavor with no advanced technique like remote ISP connection, memory scrape etc.

*But if the decompilation switch couldn't be turned off, I would have not seen any use case of this compiler.

Greeting,
Jessen
