### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by WC3D** [MScholtes/Win-PS2EXE#10]
Hello,
I received this message when trying to compile in the .Net 4.X version

`Microsoft (R) Visual C# Compiler version 4.8.9037.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

Press any key to continue . . .`

Then If I run it in the .Net 3.5 folder included

`Microsoft (R) Visual C# 2008 Compiler version 3.5.30729.9151
for Microsoft (R) .NET Framework version 3.5
Copyright (C) Microsoft Corporation. All rights reserved.

Press any key to continue . . .`

Both Compile attempts result in no GUI exe.

I am running Windows 11 64bit in a Virtual Machine. I will try on a Windows 10 PC later when I get time.

.Net Framework 2.0,3.0, 3.5,4.8.1 are installed.

Any and all help is greatly appreciated!

**Comment by MScholtes** [comment]
Hello @WC3D,

since there is no error message displayed I think the source code is compiled to executables. I have two ideas why the executables are not present:

1. They are at another place as you expect. The executables are generated in the current directory of your shell and not unconditionally in the directory of the source files.
2. A virus scanner or exploit protection removes or moves the executables directly after generation. Please check the activity logs of your security tools.

Greetings

Markus

**Comment by WC3D** [comment]
Hi Markus,

1. I don't see it in the shell folder
2. No antivirus blocks
3. Seems after reinstalling .Net 4.8.1 it is okay now. Thank you!
