### ISSUE TITLE
emoji not supported

### ISSUE THREAD

**Issue by pks888** [MScholtes/Win-PS2EXE#9]
![20211214090055](https://user-images.githubusercontent.com/3284852/145913461-3bfbffaf-282d-43b8-baba-196d3a97dd22.png)

**Comment by MScholtes** [comment]
Hello @632575987,

there are several possible reasons for this behaviour. 
First, to display special characters correctly the souce file has to be **UTF8** encoded (**UTF16** works fine too).
Second you have to check whether your console window is able to display the character set.
Third the parameter **-UNICODEEncoding** for **PS2EXE** might help. This parameter is not exposed to **Win-PS2EXE**.

You can get an impression how complicated this can be when checking this issue https://github.com/MScholtes/PS2EXE/issues/30 (this was a very unfriendly guy, but the issue was very interesting).

Please try and if it does not work please tell me about your environment (you are using **Windows Terminal**, I have no experience with it).

Greetings

Markus

**Comment by MScholtes** [comment]
Closed for no reaction
